const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=k=>{try{return JSON.parse(localStorage.getItem(k))}catch{return null}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let test,questions,answers,index,selected,stage,missed,practice=false;
const key=()=>`lesson-test:${test.id}:${test.version}`;
async function json(path){const r=await fetch(path);if(!r.ok)throw Error('読み込みに失敗しました');return r.json()}
function valid(t){return t.id&&t.version&&t.title&&Array.isArray(t.questions)&&t.questions.length&&t.questions.every(q=>q.id&&q.prompt&&Array.isArray(q.choices)&&q.choices.length>=2&&q.choices.every(x=>typeof x==='string')&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<q.choices.length&&q.explanation&&q.review&&q.hint)}
async function home(){try{const catalog=await json('data/catalog.json');app.innerHTML=`<div class="eyebrow">LESSON REVIEW</div><h1>今日の学びを、<br>自分の力に。</h1><p class="muted">タップして回答。解説で確認。苦手を見つけて、もう一度。</p><div id="tests"></div>`;const list=app.querySelector('#tests');if(!catalog.tests.length)list.innerHTML='<section class="card empty"><h2>授業テストは準備中です</h2><p>授業要約から作成したテストが、ここに追加されます。</p></section>';catalog.tests.forEach(item=>{const card=document.createElement('section');card.className='card';card.innerHTML=`<span class="badge">${esc(item.subject)}</span><h2>${esc(item.title)}</h2><p class="muted">${esc(item.description||'基礎からテスト対策まで')}</p><button class="primary wide">テストを開く</button>`;card.querySelector('button').onclick=()=>open(item.file);list.append(card)});history.replaceState(null,'',location.pathname)}catch{app.innerHTML='<section class="card"><h1>読み込めませんでした</h1><p>通信状況を確認して、ページを再読み込みしてください。</p></section>'}}
async function open(file){try{test=await json(`data/${file}`);if(!valid(test))throw Error('形式エラー');history.replaceState(null,'',`?test=${encodeURIComponent(test.id)}`);const past=read(key()+':result');app.innerHTML=`<section class="card"><span class="badge">${esc(test.subject)}</span><h1>${esc(test.title)}</h1><p>${esc(test.description||'')}</p><p>全${test.questions.length}問・1問1点</p><p class="muted">間違えたらヒントを見て再挑戦できます。得点は最初の回答で計算します。</p>${past?`<p>前回：${past.score} / ${past.total}点（${past.rate}%）</p>`:''}<div class="actions"><button id="start" class="primary">最初から始める</button>${read(key())?'<button id="resume">途中から再開</button>':''}</div></section>`;app.querySelector('#start').onclick=()=>start(false);app.querySelector('#resume')?.addEventListener('click',()=>start(true))}catch{app.innerHTML='<section class="card"><h1>テストを開けませんでした</h1><p>通信状況や問題データを確認してください。</p><a href="./">一覧へ戻る</a></section>'}}
function start(resume,subset){practice=!!subset;questions=subset||test.questions;const p=resume?read(key()):null;answers=p?.answers||[];index=answers.length;if(index>=questions.length)index=0,answers=[];reset()}
function reset(){selected=null;stage='answer';missed=false;draw()}
function draw(message=''){const q=questions[index];app.innerHTML=`<div class="progress"><span>${practice?'復習モード':esc(test.subject)}</span><span>${index+1} / ${questions.length}問</span></div><progress value="${index}" max="${questions.length}"></progress><section class="card"><span class="badge">${esc(q.level||'基礎')}</span><h2>${esc(q.prompt)}</h2><div class="options" role="group" aria-label="回答の選択肢">${q.choices.map((c,i)=>`<button class="option" data-i="${i}" aria-pressed="${selected===i}" ${stage==='done'?'disabled':''}><b>${i+1}</b><span>${esc(c)}</span></button>`).join('')}</div>${message}<button id="submit" class="primary wide" ${selected===null?'disabled':''}>${stage==='done'?(index===questions.length-1?'結果を見る':'次の問題へ'):stage==='retry'?'もう一度回答する':'回答する'}</button></section>`;app.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.i);app.querySelectorAll('[data-i]').forEach(x=>x.setAttribute('aria-pressed',String(Number(x.dataset.i)===selected)));app.querySelector('#submit').disabled=false});app.querySelector('#submit').onclick=submit}
function submit(){const q=questions[index];if(stage==='done'){index++;if(index===questions.length)return result();reset();window.scrollTo(0,0);return}if(selected===null)return;if(stage==='answer'){answers.push({id:q.id,choice:selected,correct:selected===q.answer});if(!practice)save(key(),{answers});if(selected!==q.answer){missed=true;stage='retry';selected=null;draw(`<div class="feedback wrong"><strong>もう一度考えてみよう</strong><p>ヒント：${esc(q.hint)}</p><p>最初の回答は記録しました。ヒントを使って再挑戦！</p></div>`);return}}const correct=selected===q.answer;stage='done';draw(`<div class="feedback ${correct?'':'wrong'}"><strong>${correct?(missed?'再挑戦で正解！':'正解！'):'正解を確認しよう'}</strong><p>正解：${esc(q.choices[q.answer])}</p><p>${esc(q.explanation)}</p><p><strong>復習ポイント：</strong>${esc(q.review)}</p></div>`)}
function result(){const score=answers.filter(a=>a.correct).length,rate=Math.round(score/questions.length*100),wrong=questions.filter(q=>!answers.find(a=>a.id===q.id)?.correct),good=questions.filter(q=>answers.find(a=>a.id===q.id)?.correct);if(!practice){save(key()+':result',{score,total:questions.length,rate,date:new Date().toISOString()});save(key(),null)}const review=q=>{const a=answers.find(a=>a.id===q.id);return `<article class="review"><h3>${esc(q.prompt)}</h3><p>最初の回答：${esc(q.choices[a.choice])}</p><p><strong>正解：${esc(q.choices[q.answer])}</strong></p><p>${esc(q.explanation)}</p><p><strong>復習ポイント：</strong>${esc(q.review)}</p></article>`};app.innerHTML=`<div class="eyebrow">${practice?'REVIEW RESULT':'TEST RESULT'}</div><h1>おつかれさま！</h1><section class="card"><div class="stats"><div class="score">${score}<small> / ${questions.length}点</small></div><div>正答率<br><strong>${rate}%</strong></div></div><p class="muted">最初の回答をもとに集計しています。</p><h2>${wrong.length?'次は、このポイントを復習しよう':'全問正解！よく理解できています。'}</h2>${[...new Set(wrong.map(q=>q.review))].map(p=>`<p>・${esc(p)}</p>`).join('')}<div class="actions">${wrong.length?'<button id="retry" class="primary">間違えた問題を解き直す</button>':''}<button id="again">全問もう一度</button></div></section><section class="card"><h2>間違えた問題（${wrong.length}問）</h2>${wrong.length?wrong.map(review).join(''):'<p>ありません。この調子！</p>'}</section><section class="card"><details><summary>正解した問題・解説（${good.length}問）</summary>${good.map(review).join('')}</details></section>${referenceNotes()}<a href="./">テスト一覧へ</a>`;app.querySelector('#retry')?.addEventListener('click',()=>start(false,wrong));app.querySelector('#again').onclick=()=>start(false);window.scrollTo(0,0)}
function referenceNotes(){return test.notes?.length?`<section class="card"><details><summary>授業要約の補正・確認資料</summary>${test.notes.map(n=>`<p>${esc(n)}</p>`).join('')}${(test.sources||[]).filter(s=>/^https:\/\//.test(s.url)).map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></p>`).join('')}</details></section>`:''}
home();
